services:
  - type: web
    name: kulkamps-bot
    env: python
    pythonVersion: 3.11.8
    buildCommand: |
      pip install -r requirements.txt
      playwright install
    startCommand: python main.py
